baseURL = "/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "高彰的小笔记"
rssLimit = 25

[params]
  description = "一个美国人用中文分享生活有趣的事情，有用的原则。"
  headerAllPostsText = "所有帖子"
  allPostsText = "阅读更多"
  script = '<script src="https://zhidao.johnjago.com/script.js" data-site="ZKQBUYCC" defer></script>'

[menu]
  [[menu.main]]
    name = "关于"
    url = "关于/"
    weight = 1
