baseURL = "/"
languageCode = "zh-cn"
title = "小笔记"
theme = "timeless"

[params]
  description = "生活中的小笔记"
  headerAllPostsText = "所有帖子"
  footerSymbol = "&"
  allPostsText = "阅读更多"
  serif = false

[menu]
  [[menu.main]]
    name = "英文博客"
    url = "https://johnjago.com/blog"
    weight = 1
