baseURL = "/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "小笔记"
theme = "timeless"
rssLimit = 25

[params]
  description = "一个美国人用中文分享生活有趣的事情，有用的原则。"
  headerAllPostsText = "所有帖子"
  footerSymbol = "&"
  allPostsText = "阅读更多"
  serif = false

[menu]
  [[menu.main]]
    name = "关于"
    url = "关于/"
    weight = 1
  [[menu.main]]
    name = "英文"
    url = "https://johnjago.com/blog"
    weight = 2
